
- name: enable and restart cedar-infrastructure
  service: name=cedar-infrastructure enabled=yes state=restarted

- name: enable and restart cedar-microservices
  service: name=cedar-microservices enabled=yes state=restarted

- name: enable and restart cedar-frontend
  service: name=cedar-frontend enabled=yes state=restarted

- name: enable and restart cedar
  service: name=cedar-{{ item }} enabled=yes state=restarted
  with_items:
   - infrastructure
   - microservices
   - frontend

- name: stop cedar
  service: name=cedar-{{ item }} enabled=yes state=stopped
  with_items:
   - infrastructure
   - microservices
   - frontend
